version: "3.9"

services:
  backend:
    build: ./backend
    container_name: stock_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data

  frontend:
    build: ./frontend
    container_name: stock_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
